---
version: "2"
services:
# Server
  server:
    build:
      context: ./dockerfiles
      dockerfile: Server-a.dockerfile
    image: "server"
    restart: always
    networks:
      BACKEND:
        ipv4_address: "192.168.14.11"
    cap_add:  
      - NET_ADMIN
    volumes:
      - ./traces:/mnt 
    hostname: BACKEND

# Client
  client:
    build:
      context: ./dockerfiles
      dockerfile: Client.dockerfile
    image: "client"
    restart: always
    networks:
      CLIENT:
        ipv4_address: "192.168.13.5"
    cap_add:  
      - NET_ADMIN
    volumes:
      - ./traces:/mnt 
    hostname: Client
    command: tail -f /dev/null

# Router
  router:
    build:
      context: ./dockerfiles
      dockerfile: Router.dockerfile
    image: "router"
    restart: always
    networks:
      CLIENT:
        ipv4_address: "192.168.13.10"
      BACKEND:
        ipv4_address: "192.168.14.10"
    cap_add:  
      - NET_ADMIN
    ports:
      - 9000:10000
    volumes:
      - ./traces:/mnt 
    hostname: Router

networks:
# defined BACKEND network for docker containers
  BACKEND:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.14.0/24"
  CLIENT:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.13.0/24"