---
version: "2"
services:
  
# Host
  server:
    build:
      context: ./
      dockerfile: Server-a.dockerfile
    image: "server"
    restart: always
    networks:
      LAN:
        ipv4_address: "192.168.13.11"
    volumes:
      - ./traces:/mnt 
    hostname: Server

# Client
  client:
    build:
      context: ./
      dockerfile: Client.dockerfile
    image: "client"
    restart: always
    networks:
      LAN:
        ipv4_address: "192.168.13.5"
    volumes:
      - ./traces:/mnt 
    hostname: Client
    command: tail -f /dev/null

networks:
  # defined LAN network for docker containers
  LAN:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.13.0/24"
